setup patched for mint; use can choose between aptitude and apt-get.

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Version     : 0.1
+# Version     : 0.2
 # Author      : J. Pfeffer
 # License     : GPL
 
@@ -28,8 +28,10 @@ CLEANING=true
 # Required packages ##
 # Essential packages for builiding, java (for Eclipse) and wget to download resources
 REQUIREMENTS="build-essential git openjdk-7-jre wget"
-REQUIREMENTS_DEBIAN=$REQURIREMENTS
+REQUIREMENTS_DEBIAN=$REQUIREMENTS
 REQUIREMENTS_SUSE="gcc gcc-c++ make git wget java-1_7_0-openjdk"
+
+
 
 # Libraries to install
 #REQUIREMENTS+=" libboost-all-dev"
@@ -73,14 +75,36 @@ function download()
 function install_dependencies() {
     echo "Installing requirements (calling sudo) ..."
     INSTALLOK="FALSE"
-    if [ -n "$(echo $DISTRIBUTION | grep debian)" -o -n "$(echo $DISTRO | grep ubuntu)" ]; then
-        sudo apt-get -q --show-progress install $REQUIREMENTS_DEBIAN && INSTALLOK="TRUE"
+
+    if [ -n "$(echo $DISTRIBUTION | grep debian)" -o -n "$(echo $DISTRIBUTION | grep ubuntu)" -o -n "$(echo $DISTRIBUTION | grep mint )"  ]; then
+      while [ $INSTALLOK="FALSE" ]; do
+        echo -e "You are using a debian based distribution.\nDo you want to use 'apt-get' or 'aptitude' to install dependencies?\n'1' for 'apt-get'\n'2' for 'aptitude'\n'0' to abort"
+        read -p "> " -n 1 -r DEB_CHOOSEINSTALLER
+        echo -e "\n"
+        case "$DEB_CHOOSEINSTALLER" in
+          "0")  echo "User aborted installation"
+                exit 0
+                ;;
+          "1")  sudo apt-get -q --show-progress install $REQUIREMENTS_DEBIAN && INSTALLOK="TRUE"
+                INSTALLOK="TRUE"
+                ;;
+          "2")  sudo aptitude -q install $REQUIREMENTS_DEBIAN -y		#aptitude behaves different then apt-get and if done the same way, $INSTALLOK would always be TRUE
+                if [ $? -eq 0 ]; then
+                  INSTALLOK="TRUE"
+                fi
+                ;;
+          *)    echo -e "\nChoice was not recognized. Please select 0..2."
+                INSTALLOK="FALSE"
+                ;;
+        esac
+      done
     elif [ -n "$(echo $DISTRIBUTION | grep suse)" ]; then
         sudo zypper install -l --no-recommends $REQUIREMENTS_SUSE && INSTALLOK="TRUE"
     else
         echo "Unable to determine the package manager for your distribution ($DISTRIBUTION/$DISTVERION)."
         exit 1
     fi
+    
     if  [ $INSTALLOK != "TRUE" ]; then 
         echo " Failed."
         exit 1
